name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      release_notes: ${{ steps.release_notes.outputs.NOTES }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Generate Release Notes
        id: release_notes
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          # Find the last non-beta tag by filtering out beta tags
          LAST_TAG=$(git tag -l 'v*' --sort=-v:refname | grep -v "beta" | grep -v "${CURRENT_TAG}" | head -n1 || echo "")
          
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s" --no-merges)
            COMPARE_LINK="https://github.com/$GITHUB_REPOSITORY/commits/${CURRENT_TAG}"
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s" --no-merges)
            COMPARE_LINK="https://github.com/$GITHUB_REPOSITORY/compare/${LAST_TAG}...${CURRENT_TAG}"
          fi
          
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "## ${CURRENT_TAG}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "Changes in this release:" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "---" >> $GITHUB_OUTPUT
          echo "**Full Changelog**: ${COMPARE_LINK}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-macos:
    needs: setup
    runs-on: macos-latest
    outputs:
      dep_versions: ${{ steps.get_versions.outputs.VERSIONS }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install cmake ffmpeg opencv sdl2 ncurses readline

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Os" -DCMAKE_C_FLAGS="-Os" ..
          make

      - name: Create macOS Package
        run: |
          cd build
          zip -r CMD-Media-Player-v${{ needs.setup.outputs.version }}-macos-arm64.zip CMD-Media-Player

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64-build
          path: build/CMD-Media-Player-v${{ needs.setup.outputs.version }}-macos-arm64.zip

      - name: Get Dependency Versions
        id: get_versions
        run: |
          echo "VERSIONS<<EOF" >> $GITHUB_OUTPUT
          echo "### Homebrew Dependencies of this version (macOS)" >> $GITHUB_OUTPUT
          echo "- opencv: $(brew list --versions opencv | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "- ffmpeg: $(brew list --versions ffmpeg | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "- sdl2: $(brew list --versions sdl2 | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "- ncurses: $(brew list --versions ncurses | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "- readline: $(brew list --versions readline | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  create-release:
    needs: [setup, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Check Version Type
        id: version_type
        run: |
          if [[ "${{ needs.setup.outputs.version }}" =~ .*beta.* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ needs.setup.outputs.version }}
          body: |
            ${{ needs.setup.outputs.release_notes }}
            
            ${{ needs.build-macos.outputs.dep_versions }}
          files: |
            artifacts/macos-arm64-build/*
          draft: false
          prerelease: ${{ steps.version_type.outputs.IS_PRERELEASE }}
